var PhaseMaster = [
  { key: "" , label: "" },
  { key: "1", label: "戦略策定" },
  { key: "2", label: "企画立案" },
  { key: "3", label: "ウォーターフォール/要件定義" },
  { key: "4", label: "ウォーターフォール/外部設計" },
  { key: "5", label: "ウォーターフォール/内部設計" },
  { key: "6", label: "ウォーターフォール/製造" },
  { key: "7", label: "ウォーターフォール/テスト" },
  { key: "8", label: "ウォーターフォール/移行" },
  { key: "9", label: "ウォーターフォール/導入" },
  { key: "10", label: "ウォーターフォール/保守" },
  { key: "11", label: "ウォーターフォール/運用" },
  { key: "12", label: "PKG/方向付け(inception)" },
  { key: "13", label: "PKG/推敲(elaboration)" },
  { key: "14", label: "PKG/作成（Construction）" },
  { key: "15", label: "PKG/移行(Transition）" },
  { key: "16", label: "PKG/運用（Production）" },
  { key: "17", label: "教育受講、キャリアメネジメント" },
  { key: "18", label: "人事評定" },
  { key: "19", label: "出退勤・工数管理" },
  { key: "20", label: "予算管理" },
  { key: "21", label: "監査コンプライアンス対応" },
  { key: "22", label: "総務" },
  { key: "23", label: "OFS" },
  { key: "24", label: "ISO関連(9000/14000)" },
  { key: "25", label: "業務改善" },
  { key: "26", label: "安全・健康推進" },
  { key: "27", label: "報告業務" },
  { key: "28", label: "ファイリング" },
  { key: "29", label: "その他特命" },
  { key: "30", label: "出張" },
  { key: "31", label: "有休/半休/調整休" }
];

var ActivityMaster = [
  { key: "" , label: "" },
  { key: "1", label: "検討(ワーク)" },
  { key: "2", label: "資料作成" },
  { key: "3", label: "会議・打ち合わせ" },
  { key: "4", label: "進捗管理" },
  { key: "5", label: "問題・リスク管理" },
  { key: "6", label: "コスト管理" },
  { key: "7", label: "変更管理" },
  { key: "8", label: "ゲート管理・検収" },
  { key: "9", label: "テスト立ち合い・管理" },
  { key: "10", label: "移行立ち合い・管理" },
  { key: "11", label: "プロジェクトリード" },
  { key: "12", label: "設計実務" },
  { key: "13", label: "製造実務" },
  { key: "14", label: "テスト実務" },
  { key: "15", label: "移行実務" },
  { key: "16", label: "導入・教育" },
  { key: "17", label: "保守実務" },
  { key: "18", label: "運用実務" },
  { key: "19", label: "検討・資料作成" },
  { key: "20", label: "実務作業" }
];
